name: Run API Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run tests and generate HTML report
        run: |
          pytest tests/test_validation.py --html=report.html --self-contained-html -v

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html
